//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerManagerV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jugador()
        {
            this.Huella = new HashSet<Huella>();
        }
    
        public int Rut { get; set; }
        public string DV { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public System.DateTime FechaNac { get; set; }
        public string EquipoJugador { get; set; }
        public byte[] EstadoSuspencion { get; set; }
        public Nullable<int> TarjetaAmarilla { get; set; }
        public Nullable<decimal> Gol { get; set; }
        public Nullable<int> CantPartido { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Huella> Huella { get; set; }
    }
}
