//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerManagerV1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoccerManagerV1Entities2 : DbContext
    {
        public SoccerManagerV1Entities2()
            : base("name=SoccerManagerV1Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Equipo> Equipo { get; set; }
        public DbSet<Estadio> Estadio { get; set; }
        public DbSet<Jugador> Jugador { get; set; }
        public DbSet<Partido> Partido { get; set; }
        public DbSet<RegistroFecha> RegistroFecha { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TablaPosiciones> TablaPosiciones { get; set; }
    }
}
