//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerManagerV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaPosiciones
    {
        public int Id { get; set; }
        public string NombreEqui { get; set; }
        public int PatidoJugado { get; set; }
        public int GolFav { get; set; }
        public int GolCont { get; set; }
        public int GolDif { get; set; }
        public int Puntos { get; set; }
    
        public virtual Equipo Equipo { get; set; }
    }
}
